[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.6",
    "openai==1.57.0",
    "requests>=2.32.4",
    "uvicorn==0.32.1",
]
